version: "3.5"

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  server:
    build:
      context: ../../
      dockerfile: packages/e2e/Dockerfile
    image: runtime
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn server:run
    environment:
      TYPEORM_HOST: db
      FB_OAUTH_PROFILE_URL: http://external-services:7000/facebook/profile
      GITHUB_OAUTH_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_OAUTH_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_OAUTH_AUTHORIZATION_URL: http://external-services:7000/github/authorize
    expose:
      - 9000
    depends_on:
      - db

  external-services:
    image: runtime
    command: yarn e2e:services
    environment:
      SERVER_URL: http://server:9000
    expose:
      - 7000

  e2e:
    image: runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://server:9000 -wait tcp://external-services:7000 -timeout 10s yarn test:e2e
    depends_on:
      - db
      - server
      - external-services
