version: "3.5"

# This docker-compose file runs the backend services and executes the e2e
# test suite against the backend server APIs.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  server:
    image: pairwise-runtime
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn server:prod
    environment:
      ENVIRONMENT: development
      TYPEORM_HOST: db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: postgres
      TYPEORM_CONNECTION: postgres
      TYPEORM_LOGGING: "false"
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_MIGRATIONS: dist/migrations/**/*.js
      TYPEORM_SUBSCRIBERS: dist/subscriber/**/*.js
      TYPEORM_MIGRATIONS_DIR: src/migrations
      JWT_SECRET: asfd709as7fd9s0a7f90as6f09as6dfas0
      FACEBOOK_PROFILE_URL: http://external-services:7000/facebook/profile
      FACEBOOK_TOKEN_URL: http://external-services:7000/facebook/token
      FACEBOOK_AUTHORIZATION_URL: http://external-services:7000/facebook/authorize
      GITHUB_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_AUTHORIZATION_URL: http://external-services:7000/github/authorize
      GOOGLE_PROFILE_URL: http://external-services:7000/google/profile
      GOOGLE_TOKEN_URL: http://external-services:7000/google/token
      STRIPE_SECRET_KEY: sk_test_mbG9wVyUhddtlRfqjtLJfRvZ00ZFBbvNDQ
      STRIPE_WEBHOOK_SIGNING_SECRET: whsec_Y5pDaU8C0qD723auxbamCRlYIjsSQOzq
      CLIENT_URL: http://client:3000
    expose:
      - 9000
    depends_on:
      - db

  external-services:
    image: pairwise-runtime
    command: yarn services:start
    environment:
      SERVER_URL: http://server:9000
    expose:
      - 7000

  e2e:
    image: pairwise-runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://server:9000 -wait tcp://external-services:7000 -timeout 20s yarn test:e2e
    depends_on:
      - db
      - server
      - external-services
