version: "3.5"

# This docker-compose file deploys the backend application: the database,
# the server, and the mock external services. This can be used to easily run
# the entire backend application in order to develop the frontend, or to
# write Cypress tests. This file uses a Dockerfile defined in the package
# external-services.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432

  external-services:
    image: runtime
    command: yarn services:start
    expose:
      - 7000
    ports:
      - "7000:7000"

  server:
    build: .
    image: runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://external-services:7000 -timeout 10s yarn server:run
    environment:
      TYPEORM_HOST: db
      CLIENT_APP_URL: http://127.0.0.1:3000
      FB_PROFILE_URL: http://127.0.0.1:7000/facebook/profile
      GITHUB_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_AUTHORIZATION_URL: http://127.0.0.1:7000/github/authorize
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - db
      - external-services
