version: "3.5"

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432

  external-services:
    image: runtime
    command: yarn e2e:services
    expose:
      - 7000

  server:
    build: .
    image: runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://external-services:7000 -timeout 10s yarn server:run
    environment:
      TYPEORM_HOST: db
      FB_OAUTH_SERVICE_URL: http://external-services:7000/facebook/profile
      GITHUB_OAUTH_SERVICE_URL: http://external-services:7000/github/profile
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - db
      - external-services
