version: "3.5"

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

  server:
    build:
      context: ./packages/server
    image: server
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn server:prod
    environment:
      TYPEORM_HOST: db
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - db
