version: "3.5"

# This docker-compose file deploys the backend application: the database,
# the server, and the mock external services. This can be used to easily run
# the entire backend application in order to develop the frontend, or to
# write Cypress tests.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: runtime
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn pairwise
    environment:
      TYPEORM_HOST: db
      CLIENT_URL: http://127.0.0.1:3000
      FACEBOOK_AUTHORIZATION_URL: http://localhost:7000/facebook/authorize
      FACEBOOK_TOKEN_URL: http://localhost:7000/facebook/token
      FACEBOOK_PROFILE_URL: http://localhost:7000/facebook/profile
      GITHUB_AUTHORIZATION_URL: http://localhost:7000/github/authorize
      GITHUB_TOKEN_URL: http://localhost:7000/github/token
      GITHUB_PROFILE_URL: http://localhost:7000/github/profile
      GOOGLE_TOKEN_URL: http://localhost:7000/google/token
      GOOGLE_PROFILE_URL: http://localhost:7000/google/profile
    expose:
      - 9000
    ports:
      - 7000:7000
      - 9000:9000
    depends_on:
      - db
