version: "3.5"

# This docker-compose file deploys the backend application: the database,
# the server, and the mock external services. This can be used to easily run
# the entire backend application in order to develop the frontend, or to
# write Cypress tests.
#
# NOTE: It would be great if this docker-compose could deploy the
# external-services as a separate service like the other docker-compose
# files, however there is an annoying issue with the Google authentication
# redirects during user signup that make this problematic, so here the
# server and external-services are both run concurrently in the services
# service.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432

  stripe:
    image: stripe/stripe-cli
    command: --api-key sk_test_mbG9wVyUhddtlRfqjtLJfRvZ00ZFBbvNDQ listen --forward-to=services:9000/payments/checkout-success

  services:
    build:
      context: .
      dockerfile: App.Dockerfile
    image: pairwise-dev-runtime
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn pairwise
    environment:
      TYPEORM_HOST: db
      CLIENT_URL: http://127.0.0.1:3000
      FACEBOOK_AUTHORIZATION_URL: http://localhost:7000/facebook/authorize
      FACEBOOK_TOKEN_URL: http://localhost:7000/facebook/token
      FACEBOOK_PROFILE_URL: http://localhost:7000/facebook/profile
      GITHUB_AUTHORIZATION_URL: http://localhost:7000/github/authorize
      GITHUB_TOKEN_URL: http://localhost:7000/github/token
      GITHUB_PROFILE_URL: http://localhost:7000/github/profile
      GOOGLE_TOKEN_URL: http://localhost:7000/google/token
      GOOGLE_PROFILE_URL: http://localhost:7000/google/profile
    expose:
      - 9000
    ports:
      - 7000:7000
      - 9000:9000
    depends_on:
      - db
      - stripe
