version: "3.5"

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432

  server:
    build: .
    image: runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://external-services:7000 -timeout 10s yarn server:run
    environment:
      TYPEORM_HOST: db
      CLIENT_APP_URL: http://client:3000
      FB_OAUTH_SERVICE_URL: http://external-services:7000/facebook/profile
      GITHUB_OAUTH_SERVICE_URL: http://external-services:7000/github/profile
      FB_OAUTH_PROFILE_URL: http://external-services:7000/facebook/profile
      GITHUB_OAUTH_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_OAUTH_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_OAUTH_AUTHORIZATION_URL: http://external-services:7000/github/authorize
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - db
      - external-services

  external-services:
    image: runtime
    command: yarn e2e:services
    environment:
      SERVER_URL: http://server:9000
    expose:
      - 7000
