version: "3.5"

# This docker-compose file runs the backend services and executes the Cypress
# test suite against the client application.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  server:
    build:
      context: ../../
      dockerfile: packages/e2e/Dockerfile
    image: pairwise
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn server:run
    environment:
      TYPEORM_HOST: db
      CLIENT_APP_URL: http://client:3000
      FB_PROFILE_URL: http://external-services:7000/facebook/profile
      GITHUB_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_AUTHORIZATION_URL: http://external-services:7000/github/authorize
    expose:
      - 9000
    ports:
      - "9000:9000"
    depends_on:
      - db

  client:
    image: pairwise
    command: yarn client:prod
    expose:
      - 3000
    ports:
      - "3000:3000"

  external-services:
    image: pairwise
    command: yarn e2e:services
    environment:
      SERVER_URL: http://server:9000
    expose:
      - 7000

  cypress:
    image: pairwise
    command: dockerize -wait tcp://db:5432 -wait tcp://client:3000 -wait tcp://server:9000 -wait tcp://external-services:7000 -timeout 20s yarn test:cypress
    depends_on:
      - db
      - server
      - client
      - external-services
    volumes:
      - ./screenshots:/usr/app/packages/cypress/screenshots
