version: "3.5"

# This docker-compose file runs the backend services and executes the Cypress
# test suite against the client application.

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  server:
    image: pairwise-runtime
    command: dockerize -wait tcp://db:5432 -timeout 10s yarn server:prod
    environment:
      TYPEORM_HOST: db
      CLIENT_URL: http://client:3000
      FACEBOOK_PROFILE_URL: http://external-services:7000/facebook/profile
      FACEBOOK_TOKEN_URL: http://external-services:7000/facebook/token
      FACEBOOK_AUTHORIZATION_URL: http://external-services:7000/facebook/authorize
      GITHUB_PROFILE_URL: http://external-services:7000/github/profile
      GITHUB_TOKEN_URL: http://external-services:7000/github/token
      GITHUB_AUTHORIZATION_URL: http://external-services:7000/github/authorize
      GOOGLE_PROFILE_URL: http://external-services:7000/google/profile
      GOOGLE_TOKEN_URL: http://external-services:7000/google/token
    expose:
      - 9000
    ports:
      - 9000:9000
    depends_on:
      - db

  client:
    image: pairwise-runtime
    command: yarn client:prod
    expose:
      - 3000
    ports:
      - 3000:3000

  external-services:
    image: pairwise-runtime
    command: yarn services:start
    environment:
      SERVER_URL: http://server:9000
    expose:
      - 7000

  cypress:
    image: pairwise-runtime
    command: dockerize -wait tcp://db:5432 -wait tcp://client:3000 -wait tcp://server:9000 -wait tcp://external-services:7000 -timeout 20s yarn test:cypress
    depends_on:
      - db
      - server
      - client
      - external-services
    ipc: host # See: https://github.com/cypress-io/cypress/issues/350#issuecomment-267704772
    volumes:
      - ./docker-screenshots:/usr/app/packages/cypress/screenshots
