version: "3.5"
services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql:/var/lib/postgresql
