name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Build dependencies container
        run: yarn docker:build
      - name: Run e2e API Tests
        run: yarn e2e
        env:
          CI: true
      - name: Run Cypress Tests
        run: yarn cypress
        env:
          CI: true
