# This is the source of truth for Pairwise Production.
#
# This workflow deploys the server and both client applications to
# production. It runs whenever a commit hits master. The deployments are
# as follows:
#
# - Server: Deployed to Google Cloud Run
# - Client Workspace: Deployed with Netlify
# - WWW Landing Page: Deployed via Google with Cloud Storage
#
# This workflow builds everything and runs the same full test suite which
# runs against pull requests and then deploys each of the applications. It
# takes a long time to run, but it is glorious.

# Reference docs:
# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
# https://cloud.google.com/run/docs/building/containers

name: Deploy Production

# Only deploy on commits to the master branch
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  CI: true
  RUN_REGION: us-central1
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  PRODUCTION_SERVER_URL: ${{ secrets.PRODUCTION_SERVER_URL }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_WORKSPACE_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WORKSPACE_SITE_ID }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  CLIENT_SENTRY_DSN: ${{ secrets.CLIENT_SENTRY_DSN }}
  SLACK_STATUS_BOT_ACCESS_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup NodeJS
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # Install dependencies, if any package.json or lock files have changed
      - name: Install and cache dependencies
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: bonham000
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          dockerfile: Base.Dockerfile
          image_name: pairwise-dependencies

      # Build the application
      - name: Build the application
        run: yarn docker:build:ci_deploy

      # Run all package unit tests
      - name: Run static and unit tests
        run: yarn docker:test

      # Run e2e tests
      - name: Run e2e tests
        run: yarn e2e

      # Run Cypress tests
      - name: Run Cypress tests
        run: yarn cypress

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      # Configure gcloud CLI
      - name: Setup gcloud CLI
        run: |
          gcloud config set project $CLOUD_RUN_PROJECT_ID

      # Configure Docker to use gcloud
      - name: Configure Docker with gcloud
        run: gcloud auth configure-docker

      # Build the server application directly (instead of using Google Cloud Build)
      - name: Build the production server application
        run: |
          docker build \
            --tag gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA \
            -t pairwise-production \
            -f packages/server/Dockerfile .

      # Push the production server image to gcloud
      - name: Push the production server image to GCR
        run: docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA

      # Deploy the image to Cloud Run
      - name: Deploy the production server to Google Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA \
            --platform managed

      # Build the client application directly (instead of using Netlify)
      - name: Build the production client application
        run: |
          docker build \
            --build-arg REACT_APP_HOST=$PRODUCTION_SERVER_URL \
            --build-arg REACT_APP_STRIPE_API_KEY=$STRIPE_PUBLISHABLE_KEY \
            --build-arg REACT_APP_SENTRY_DSN=$CLIENT_SENTRY_DSN \
            -t pairwise-production-client \
            -f packages/client/Dockerfile .

      # Deploy client workspace on Netlify (no builds occur on Netlify)
      # (docs: https://github.com/netlify/cli/blob/master/docs/commands/deploy.md)
      # Note that in Netlify the production branch is set to some non-existent
      # branch, "master-x", to prevent automatically publishing. The only path to
      # publish the production client is this step right here:
      - name: Deploy the client workspace to Netlify
        run: |
          docker run \
            --env GITHUB_SHA=$GITHUB_SHA \
            --env NETLIFY_SITE_ID=$NETLIFY_SITE_ID \
            --env NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN \
            -t pairwise-production-client

      # NOTE: We need the static files to be available to the host environment,
      # thus the use of volumes here. This is because we want to use the
      # authenticated and authorized gsutil to deploy the site, and if we
      # dropped gsutil into the docker container we would have to auth another
      # way
      - name: Build the pairwise.tech static site
        run: |
          docker run \
            --rm -v "$PWD/packages/www/public:/usr/app/packages/www/public:rw" pairwise-dependencies /bin/bash -c 'yarn www:build'

      # Deploy the static WWW site to Cloud Storage
      - name: Deploy pairwise.tech static site
        run: gsutil -m rsync -r packages/www/public gs://www.pairwise.tech

      # Send Slack notification if workflow succeeds
      # (docs: https://github.com/voxmedia/github-action-slack-notify-build)
      - name: Notify Slack on workflow success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: SUCCESS
          color: good

      # Send Slack notification if workflow fails
      - name: Notify Slack on workflow failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: FAILED
          color: danger
