# This workflow deploys the production server to Google Cloud Run and
# the client workspace to Netlify. It's triggered by any commits to
# the master branch. The landing page is deployed separately using ZEIT Now.

# Reference docs:
# https://github.com/GoogleCloudPlatform/github-actions/blob/master/example-workflows/cloud-run/.github/workflows/cloud-run.yml
# https://cloud.google.com/run/docs/building/containers

name: Deploy Production

# Only deploy on commits to the master branch
on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  CI: true
  RUN_REGION: us-central1
  CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
  CLOUD_RUN_PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
  GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
  PRODUCTION_SERVER_URL: ${{ secrets.PRODUCTION_SERVER_URL }}
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_WORKSPACE_AUTH_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_WORKSPACE_SITE_ID }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  SLACK_STATUS_BOT_ACCESS_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Setup NodeJS
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # Install the application dependencies
      - name: Install dependencies
        run: yarn docker:dependencies

      # Build the application
      - name: Build the application
        run: yarn docker:build

      # Run all package unit tests
      - name: Run static and unit tests
        run: yarn docker:test

      # Run e2e tests
      - name: Run e2e tests
        run: yarn e2e

      # Run Cypress tests
      - name: Run Cypress tests
        run: yarn cypress

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}

      # Configure gcloud CLI
      - name: Setup gcloud CLI
        run: |
          gcloud config set project $CLOUD_RUN_PROJECT_ID

      # Configure Docker to use gcloud
      - name: Configure Docker with gcloud
        run: gcloud auth configure-docker

      # Build the server application directly (instead of using Google Cloud Build)
      - name: Build the production server application
        run: |
          docker build -t pairwise-production --tag gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA -f packages/server/Dockerfile .

      # Push the production server image to gcloud
      - name: Push the production server image to GCR
        run: docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA

      # Deploy the image to Cloud Run
      - name: Deploy the production server to Google Cloud Run
        run: |
          gcloud run deploy $CLOUD_RUN_SERVICE_NAME \
            --region $RUN_REGION \
            --image gcr.io/$CLOUD_RUN_PROJECT_ID/$CLOUD_RUN_SERVICE_NAME:$GITHUB_SHA \
            --platform managed

      # Build the client application directly (instead of using Netlify)
      - name: Build the production client application
        run: |
          docker build \
            --build-arg STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY \
            --build-arg REACT_APP_HOST=$PRODUCTION_SERVER_URL \
            -t pairwise-production-client \
            -f packages/client/Dockerfile .
      # Deploy client workspace on Netlify (no builds occur on Netlify)
      # (docs: https://github.com/netlify/cli/blob/master/docs/commands/deploy.md)
      # Note that in Netlify the production branch is set to some non-existent
      # branch, master-x, to prevent automatically publishing. The only path to
      # publish the production client is this step right here:
      - name: Deploy the client workspace to Netlify
        run: docker run --env NETLIFY_SITE_ID=$NETLIFY_SITE_ID --env NETLIFY_AUTH_TOKEN=$NETLIFY_AUTH_TOKEN --env GITHUB_SHA=$GITHUB_SHA -t pairwise-production-client

      # NOTE: We need the static files to be available to the host environment,
      # thus the use of volumes here. This is because we want to use the
      # authenticated and authorized gsutil to deploy the site, and if we
      # dropped gsutil into the docker container we would have to auth another
      # way
      - name: Build the pairwise.tech static site
        run: docker run --rm -v "$PWD/packages/www/public:/usr/app/packages/www/public:rw" pairwise-dependencies /bin/bash -c 'yarn www:build'

      # Deploy the static WWW site to Cloud Storage
      - name: Deploy pairwise.tech static site
        run: gsutil -m rsync -r packages/www/public gs://www.pairwise.tech

      # Send Slack success notification
      # (docs: https://github.com/voxmedia/github-action-slack-notify-build)
      - name: Notify Slack on workflow success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: SUCCESS
          color: good

      # Send Slack failure notification
      - name: Notify Slack on workflow failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: FAILED
          color: danger
