name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # - name: Run the e2e test suite
      #   run: yarn e2e
      #   env:
      #     CI: true
      - name: Run the Cypress test suite
        run: yarn cypress
        env:
          CI: true
