name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install and cache dependencies
        # Docs: https://github.com/marketplace/actions/build-docker-images-using-cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: bonham000
          # No need to manually set this secret. GitHub does it on your behalf:
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: pairwise-dependencies
          dockerfile: Base.Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: bonham000
          password: "${{ secrets.GITHUB_TOKEN }}"

      # Build the application
      - name: Build application
        run: yarn docker:build:ci

      # Run all package unit tests
      - name: Run static and unit tests
        run: yarn docker:test

      # Run e2e tests
      - name: Run e2e tests
        run: yarn e2e

      # Run Cypress tests
      - name: Run Cypress tests
        run: yarn cypress
