# This workflow runs tests against pull requests. The workflow runs unit
# tests for all packages and the e2e test suite. In favor or speed the test
# workflow omits the client package build and the cypress tests. These are
# run in the full deploy pipeline before app deployments.
name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      # Install dependencies, if any package.json or lock files have changed
      - name: Install and cache dependencies
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: bonham000
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          dockerfile: BaseCache.Dockerfile
          image_name: pairwise-dependencies

      # Build the packages
      - name: Build packages
        # run: yarn docker:build:ci_test
        # [1] Enable this for a full build if you want to enable Cypress:
        run: yarn docker:build:ci_deploy

      # Run all package unit tests
      - name: Run static and unit tests
        run: yarn docker:test

      # Run e2e tests
      - name: Run e2e tests
        run: yarn e2e

      # Run Cypress tests
      # [2] Enable this step to run the Cypress tests for PR workflows:
      - name: Run Cypress tests
        run: yarn cypress

      # Send Slack notification if workflow succeeds
      # (docs: https://github.com/voxmedia/github-action-slack-notify-build)
      - name: Notify Slack on workflow success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: SUCCESS
          color: good

      # Send Slack notification if workflow fails
      - name: Notify Slack on workflow failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_STATUS_BOT_ACCESS_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: CTBG8AT0B
          status: FAILED
          color: danger